### ISSUE TITLE
似乎不能用了

### ISSUE THREAD

**Issue by lixiaoyan** [vilic/wordsbaking-plus-chrome#8]
另: 有接收捐赠的途径么 (

**Comment by vilic** [comment]
刚刚还在看新的词典 API 来着, 数据结构基本上完全变了,,, 所以这次要抽 "空" 来改. 比起捐赠, PR 更棒~

新 API 样本: https://www.bing.com/api/v6/dictionarywords/search?q=test&appid=371E7B2AF0F9B84EC491D731DF90A55719C7D209&mkt=en-us&pname=bingdict&dtype=lex

**Comment by MarlonFan** [comment]
在适配新api的时候被结构搞得有点蒙, 不知道有老版本的api结构么?

**Comment by maolion** [comment]
我在修改，也许明后几天可以适配完
中国市场API： [https://www.bing.com/api/v6/dictionarywords/search?q=test&appid=371E7B2AF0F9B84EC491D731DF90A55719C7D209&mkt=zh-cn&pname=bingdict&dtype=lex]( https://www.bing.com/api/v6/dictionarywords/search?q=test&appid=371E7B2AF0F9B84EC491D731DF90A55719C7D209&mkt=zh-cn&pname=bingdict&dtype=lex)

**Comment by MarlonFan** [comment]
还挖到一个api..
```
http://fanyi.youdao.com/openapi.do?keyfrom=Youdao-workflow&key=1738796775&type=data&doctype=json&version=1.1&q=test
```

**Comment by vilic** [comment]
@MarlonFan 你可以把百度翻译的 API 换了哈哈哈, 一般都是月初额度马上用完~

**Comment by MarlonFan** [comment]
@vilic get~ 狮子pr提交了把百度api替换掉~  有道的信息好像比它的更全一点.. :)

**Comment by maolion** [comment]
@vilic @MarlonFan 哈哈 我昨天把百度接口账号那个改了下，不默认提供账号 需要使用者自己在options页面里配置相关的账号 用他自己的

**Comment by vilic** [comment]
@maolion 咦这个倒是不错~

**Comment by vilic** [comment]
@MarlonFan @maolion 你们俩看着办~ 我坐等~

**Comment by halfcrazy** [comment]
chrome 商店更新了吗

**Comment by vilic** [comment]
@halfcrazy 还有点小 bug, 今天 @maolion 回去修好就发.

**Comment by vilic** [comment]
@halfcrazy @lixiaoyan @MarlonFan 商店今天上午已经更新了哈~
